import React, { useState, useEffect } from "react";
import { Card, Loader, FormField } from "../components";

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [posts, setPosts] = useState(false);
  const [searchtext, setSearchText] = useState("");
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328]">
          The Community ShowCase
        </h1>
        <p className="mt-2 text-[#666e75] text=[16px] max-w-[500px]">
          Browser through a collection of imaginative and visually stunning
          generated by DALLE
        </p>
      </div>
      <div className="mt-16">
        <FormField />
      </div>
      <div className="mt-10 ">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchtext && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3 ">
                showing results for <span>{searchtext}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3"></div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
