import React, { useState, useEffect } from "react";
import { Card, Loader, FormField } from "../components";

const RenderCards = ({ data, title }) => {
  if (data.length > 0)
    return data.map((post,i) => <Card key={i} {...post} />);
  return (
    <h2 className="mt-2 font-bold uppercase text-[#6449ff] text-xl">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [posts, setPosts] = useState([]);
  const [searchtext, setSearchText] = useState("");
  const [searchResults, setSearchedResults] = useState(null);
  const [searchTimeout, setSeachTimeout] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      try {
        const response = await fetch("https://dalle-qgms.onrender.com/api/v1/post/", {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        });
        
        if (response.ok) {
          const result = await response.json();
          console.log(result)
          setPosts(result.data.reverse());
        }
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    };
    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);
    setSeachTimeout(
      setTimeout(() => {
        const searchResults = allPosts.filter(
          (item) =>
            item.name.toLowerCase().includes(searchtext.toLocaleLowerCase()) ||
            item.prompt.toLowerCase().includes(searchtext.toLocaleLowerCase())
        );
        setSearchedResults(searchResults);
      }, 500)
    );
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328]">
          The Community ShowCase
        </h1>
        <p className="mt-2 text-[#666e75] text=[16px] max-w-[500px]">
          Browser through a collection of imaginative and visually stunning
          generated by DALLE
        </p>
      </div>
      <div className="mt-16">
        <FormField type="text" labelName="search posts" name="text" placeholder="Search Posts" value={searchtext} handleChange={handleSearchChange}/>
      </div>
      <div className="mt-10 ">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchtext && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3 ">
                showing results for <span>{searchtext}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchtext ? (
                <RenderCards data={searchResults} title="No search results Found" />
              ) : (
                <RenderCards data={posts} title="No Posts Found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
